baseURL: https://yiliuwang.netlify.app/
languageCode: en-us
title: Portfolio website for Yiliu Wang
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      THIS IS A PORTOFOLIO WEBSITE DEMONSTRATING INFORMATION ABOUT MYSELF AND MY DATA WORK BY FAR.
    title: Hi, my name is Yiliu Wang
  blog: {}
  contact:
    address:
      - city: London, NW1 4SA
        country: United Kingdom
        street: London Business School, Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ywang.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: Available upon request
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/YiliuWang
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.cn/incareer/in/yiliu-suzy-wang-9298831aa
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Download my resume
        url: [Download docs]docs/Yiliu_Wang_Resume.pdf
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
      - name: Generic Blog
        url: blogs/ipsum
      - name: Elements
        url: docs/Yiliu_Wang_Resume.pdf
    menu: Menu
    subtitle: Portfolio Website 
    title: Yiliu Wang
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Studying at LBS
        title: About Me
        url: blogs/aboutme
      - image: pic02.jpg
        subtitle: Learn more about my experience
        title: Resume
        url: blogs/resume
      - image: pic03.jpg
        subtitle: Lorem Etiam Nullam
        title: Homework 1
        url: blogs/homework1
      - image: pic04.jpg
        subtitle: Nisl Sed Aliquam
        title: Homework 2
        url: blogs/ipsum
      - image: pic05.jpg
        subtitle: Ipsum Dolor Sit Amet
        title: Homework 3
        url: blogs/ipsum
      - image: pic06.jpg
        subtitle: Feugiat Amet Tempus
        title: Risk Return
        url: blogs/risk_return
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: More introduction
    url: blogs
