baseURL: https://yiliuwang.netlify.app/
languageCode: en-us
title: Portfolio website for Yiliu Wang
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      THIS IS A PORTOFOLIO WEBSITE DEMONSTRATING INFORMATION ABOUT MYSELF AND MY DATA WORK BY FAR.
    title: Hi, my name is Yiliu Wang
  blog: {}
  contact:
    address:
      - city: London, NW1 4SA
        country: United Kingdom
        street: London Business School, Regent's Park
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: ywang.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: Available upon request
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Content by Yiliu Wang
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.cn/incareer/in/yiliu-suzy-wang-9298831aa
      - icon: fa-github
        label: GitHub
        url: https://github.com/YiliuWang
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/TINYTOTw?s=09
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Data Projects
        url: blogs
    links:
      - name: Home
        url: '#'
      - name: About Me
        url: aboutme
      - name: Download My Resume
        url: docs/Yiliu_Wang_Resume.pdf
    menu: Menu
    subtitle: Portfolio Website 
    title: Yiliu Wang
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Studying at LBS
        title: About Me
        url: aboutme
      - image: norway.jpg
        subtitle: Learn more about my experience
        title: Resume
        url: docs/Yiliu_Wang_Resume.pdf
      - image: mypic1.jpg
        subtitle: Rents in SF, IMDB Analysis, Retuns of Stocks, Spotify
        title: Homework 1
        url: blogs/homework1
      - image: mypic2.jpg
        subtitle: Climate & Temperature, Byden's Approval, Rentals in TFL Bikes, Renewable Energy Production
        title: Homework 2
        url: blogs/homework2
      - image: london.jpg
        subtitle: Youth Risk Behaviour, IMDB Ratings, Pay Discrimination, Brexit, GDP Development
        title: Homework 3
        url: homework3.html
      - image: yunnan.jpg
        subtitle: An Example from Our Professor Kostis
        title: Risk Return
        url: blogs/risk_return
  two:
    buttonText: Find out more about my data projects
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \r\n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \r\n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \r\n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\r\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: More introduction
    url: blogs
